name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
    
      - name: make config file
        run: |
          cd ./src/main/resources
          touch ./application.yml ./application-dev.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./application.yml 
          echo "${{ secrets.APPLICATION_DEV_YML }}" >> ./application-dev.yml
        shell: bash
    
      - name: Build with Gradle
        run: sudo ./gradlew clean build -x test
      
      - name: docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_REPO }}
        
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo docker stop prod-server
            sudo docker rm prod-server
            sudo docker image rm ${{ secrets.DOCKER_REPO }}
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_REPO }}
